### ISSUE TITLE
Create Milestones and add features in each milestone for Features on Knitting Library

### ISSUE THREAD

**Issue by mariobehling** [fashiontec/knitapps#18]
Milestone 1
Due by June 10, 2015

Milestone 2
Due by June 26, 2015

Milestone 3
Due by July 25, 2015

Milestone 4
Due by August 21, 2015 

Also refer to https://github.com/fashiontec/knitapps/issues/15

**Comment by shiluka** [comment]
**Milestone 1 :**

* Design the abstraction layers of the library
* Design the structure of the library
* Implement the structure of the library
* Implement the functions which are related to communication based on ayab 
	* Test cases for the functions
	* Documentation of the functions
* Implement the functions that are related to image based on ayab
	* Test cases for the functions  
	* Documentation of the functions

**Milestone 2:**

* Implement command line tool 
	* Test cases on command line tool
	* Documentation of the command line tool
* Implement file I/O handling functions
	* Test cases for the functions
	* Documentation of the functions

**Milestone 3:**

* Implement the functions for the disk emulator
	* Test cases on disk emulator
	* Documentation on disk emulator
* Add arduino support for knitlib
* Implement the functions that are related to the firmware 
	* Test cases on firmware
	* Documentation on firmware
* Finalize the command line tool
* Deploy knitlib on ayab system 
* Deploy knitlib on web backend

**Milestone 4:**

* Deploy the installation setup of the library
* Finalize the tests on the library
* Finalize the documentation of the library
* Create tutorials on how to use knitlib

**Comment by mariobehling** [comment]
@shiluka Please also add some more info on the choice of the technologies and development tools used.
