### ISSUE TITLE
Design and Structure of the library (knitlib)

### ISSUE THREAD

**Issue by shiluka** [fashiontec/knitapps#19]

**Comment by shiluka** [comment]
**Design of the library** : The library is designed as set of modules. Each module is self contained and independent from other modules. With the installation of the library all the dependencies should be automatically installed. 

* serial communication : open, configure, read and write to serial port
* image handling functions : memory allocation, read image file, setter and getter for image pixels
* file handling functions : read / write access
* disk emulator functions : emulate disk drive


![basic design of the library](https://cloud.githubusercontent.com/assets/4003134/7785323/03f788d6-01a9-11e5-8a8d-565814fb6032.jpg)




**Basic Structure of the library** 


knitlib/
...........\__init\__.py
...........command_line.py
		
		communication/		       # Serial communication handling
			__init.py__
			communication.py
			
		image/				       # image handling functions
			__init__.py
			image.py
			
		firmware/				       # for the firmware
			__init__.py
			firmware.py
		
		emulator/				       # Disk emulator
			__init__.py
			emulate.py
			
		fileio/				       # Read / Write image to disk
			__init__.py
			fileio.py
		
			
		exception/				# For exceptions handle
			__init__.py
			exception.py
			
		tests/					# for test purposes
			__init__.py
			test_communication.py
			test_image.py
			test_firmware.py
			test_emulate.py
			test_fileio.py
			test_machine.py
			test_exception.py

setup.py	
MANIFEST.in
README.rst
.gitignore

[https://github.com/fashiontec/knitlib](https://github.com/fashiontec/knitlib)

**Comment by tian2992** [comment]
Please bear in mind that the current communication.py on AYAB is not a general abstraction. It only works for communication with AYAB shields, not for Knittic, nor for the disk emulation hack. 

Some recomendations on building Python modules can be found here: http://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/ Please use git branches and add tests whenever adding code.

**Comment by shiluka** [comment]
@tian2992 Thanks for the valuable suggestions and references.
