### ISSUE TITLE
What's the difference between AYAB and Knittic?

### ISSUE THREAD

**Issue by andibraeu** [fashiontec/knitapps#2]
Compare both solutions. Take a look on features, software architecture and UI.

**Comment by tian2992** [comment]
http://www.knitic.com/ http://ayab-knitting.com/

**Comment by mariobehling** [comment]
@tian2992 Thanks for the links. Could explain a bit more about those two applications? What is the difference?

**Comment by mariobehling** [comment]
@sameeragunarathne @shiluka Could you help with this please? What is your understanding? What are the different technologies? It would be great to clear this question up.

**Comment by sameeragunarathne** [comment]
As I have reviewed I could see following differences between AYAB and Knittic. 
1.  Knittic uses pixelated image in the GUI as the input is given.
2.  Knittic gives image editing functionality within the GUI itself.
3.  Knittic gives more information of the knitting process including knitting direction, stitch details etc.

These features can also be developed in AYAB for enhance user experience. I would like to know the intended web interface expectations and requirement details as I can suggest detailed implementation on top of that. The current idea is to implement REST end points using python to be used by the GUI.

**Comment by shiluka** [comment]
Ayab interface
![screenshot_ayab_interface](https://cloud.githubusercontent.com/assets/4003134/7555868/d35d09a2-f777-11e4-9641-f71b1fc8935b.PNG)

Knittic interface
![screenshot_knittic_interface](https://cloud.githubusercontent.com/assets/4003134/7555874/224b8778-f778-11e4-8604-3aeff6381325.png)

**Comment by mariobehling** [comment]
@sameeragunarathne Good analysis. Please make proposals for a web interface https://github.com/fashiontec/knitapps/issues/7

**Comment by shiluka** [comment]
Differences on implementation

Ayab needs several dependency libraries such as pillow, pyserial, wsgiref, fysom and yapsy with relevant versions. 
Ayab has a plugin system which is written in python

Knittic doesn't have setup for windows 64 bit.
Knittic has a library which includes jar files
