### ISSUE TITLE
What is the deployment case for flask compared to Angular/Node/Backbone.js

### ISSUE THREAD

**Issue by mariobehling** [fashiontec/knitapps#20]
As discussed in several issues like here https://github.com/fashiontec/knitapps/issues/17, flask seems like a good solution for the web app and pattern editor. However to be sure we have taken everything in account, what is the process to get the web app running?

Deployment is an important question. What is the process to install the app compared to e.g. Angular/Nodejs?

Think of a standard user, who would like to install the app. Currently Ayab can be installed e.g. on Windows very easily.

**Comment by sameeragunarathne** [comment]
I am going to deploy the application in godaddy which I can get a hosting
space from one of my university friend. Therefore web application should
give each user a account with credentials where application should save
them in a cloud data base. Once user is created a account he will be need
to login to get access to the application.

On Fri, May 29, 2015 at 9:29 AM, Mario Behling <notifications@github.com>
wrote:

> Assigned #20 <https://github.com/fashiontec/knitapps/issues/20> to
> @sameeragunarathne <https://github.com/sameeragunarathne>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fashiontec/knitapps/issues/20#event-316839405>.
>



-- 
*Sameera Gunarathne*
Undergraduate of Department of Computer Science & Engineering of University
of Moratuwa

*+94714155561
<http://s.wisestamp.com/links?url=tel%3A%252B94716320074&sn=dmlwdWxhc2QyMDA3NEBnbWFpbC5jb20%3D>*

**Comment by mariobehling** [comment]
@sameeragunarathne This is not the question. The question is how others can install the app on their own computer. It is not the goal to depend on you. The goal is, that people can install this app on their own PC easily. So, I wonder if we need a server set up. It is possible to set up flask on the PC without a server as far as I understand, but this is only recommended for tests and developments. 

Alternatively, Angular/Node.js or similar does not need a server. 

So, what is the deployment case for flask compared to Angular/Node/Backbone.js?

**Comment by sameeragunarathne** [comment]
Hi,

For the full deployment of application, flask gives several options[1].
There should be a server apache/nginx up and running to run the application
using wsgi(web server gateway interface) files. For using apache server
running inside windows/ubuntu systems can use mod_wsgi which is a apache
module which supports python. Therefore simply configuring the routing to
the wsgi file in apache server virtual host file can run the app in the
user environment. The nginx server can be used for deploying using uWSGI
option. uWSGI configuration can be configured in a .ini file and user has
to simply run the file using commang uwsgi app_name.ini file.

Above both ways are applicable in windows/ubuntu environments.

[1]:http://flask.pocoo.org/docs/0.10/deploying/

On Fri, May 29, 2015 at 6:00 PM, Mario Behling <notifications@github.com>
wrote:

> @sameeragunarathne <https://github.com/sameeragunarathne> This is not the
> question. The question is how others can install the app on their own
> computer. It is not the goal to depend on you. The goal is, that people can
> install this app on their own PC easily. So, I wonder if we need a server
> set up. It is possible to set up flask on the PC without a server as far as
> I understand, but this is only recommended for tests and developments.
>
> Alternatively, Angular/Node.js or similar does not need a server.
>
> So, what is the deployment case for flask compared to
> Angular/Node/Backbone.js?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fashiontec/knitapps/issues/20#issuecomment-106790401>.
>



-- 
*Sameera Gunarathne*
Undergraduate of Department of Computer Science & Engineering of University
of Moratuwa

*+94714155561
<http://s.wisestamp.com/links?url=tel%3A%252B94716320074&sn=dmlwdWxhc2QyMDA3NEBnbWFpbC5jb20%3D>*
