### ISSUE TITLE
Using Rapspi instead of Arduino in Knitting Machine

### ISSUE THREAD

**Issue by mariobehling** [fashiontec/knitapps#21]
Could it be an option to use a Rapspi instead of an Arduino in Knitting Machines in Future? From a dicussions with Andi, I understand the questions is, if there are enough connectors.

**Comment by chris007de** [comment]
Basically: Everything is possible if you put enough effort on it.
But before asking whether it is possible, please provide information about the background of our question.
Why do you want to do that? 
For which knitting machine hack?
Not everything which is possible is also reasonable to do.

From the engineering side:
Handling the GPIO directly with the pins of the Raspi is not reasonable, as it is a waste of pins and you are in need of driver ICs anyway (a Raspi can't provide the 12-16V the knitting machine expects).
The Raspi is able to handle I2C connections, so it is basically possible to attach the AYAB shield to it, which provides the drivers.
But everything stands and falls with the latency of the controller. The Raspberry _might_ be to slow to implement the needle selection based on the current state of the carriage fast enough (depending on how this logic is implemented, of course. But basically, the Raspi has to handle a whole operating system with all the implications, whereas the Mikrocontroller of the Arduino is dedicated to its work).

And: It's called Raspi, not Rapspi :)

**Comment by mariobehling** [comment]
The background of the question is basically, if it would be possible to reduce complexity (and therefore different parts where something can go wrong) and potentially cost, e.g. think of a knitting machine that we can access through a mobile app directly. Your insights already show, that it is currently not an option to pursue the "unification of a Raspi and an the Arduino parts". Thanks a lot!
