### ISSUE TITLE
Generating a pixelated pattern and identify each cell as a editable unit

### ISSUE THREAD

**Issue by sameeragunarathne** [fashiontec/knitapps#26]
This issue will track on how to pixelate the pattern and how to identify each cell to make it a editable one. In this way each cell can be edited individually using the tools inside pattern editor( i.e colour configuration).

**Comment by sameeragunarathne** [comment]
Each pixel in the pixel grid is identified by the actual pixel coordinate of the mouse pointer and checking whether the mouse pointer is at the relevant pixel in the pixel grid.

**Comment by mariobehling** [comment]
Moving it to M2 as M1 is overdue.

**Comment by sameeragunarathne** [comment]
finding of a pixel coordinate is triggered by a mouse event(i.e mouse over) and take x,y coordinate values of the canvas and convert them to the pixel grid scale.(x or y coordinate/num of pixels in the grid at a side).
eg: 300/100. 
status:done
