### ISSUE TITLE
Implementation of the basic pattern editor tools

### ISSUE THREAD

**Issue by sameeragunarathne** [fashiontec/knitapps#27]
This issue is to track on the pattern editor tools which are resides inside patten editor. following tools are implemented during this task.
1. selecting pattern/region of the pattern
2. drawing tools
3. colour palette and colour picker
4. tools for pattern rotating, replicating, re-sizing,cropping etc.

**Comment by sameeragunarathne** [comment]
Current Progress

1. selecting pattern/region of the pattern (on going)
2. drawing tools (TO DO)
3. colour palette and colour picker (ongoing, implemented colour picker)
4. tools for pattern rotating, replicating, re-sizing,cropping etc. (TO DO)

**Comment by mariobehling** [comment]
As we are long over M1 I am moving this issue to M2

**Comment by sameeragunarathne** [comment]
1. selecting pattern/region of the pattern: done
2. drawing tools: started and implemented colour fill tool

**Comment by sameeragunarathne** [comment]
Most of the implementation of the basic pattern editor tools are done by now. Following are the completed and mostly complete implementations of the pattern editor.

1. Selecting of the region of the pattern from the pixelated pattern grid and ability to edit the colour details of the selected area. User also able to revert the changes. 
Improvements to be done for the feature: Identify pattern colour boundaries of the selected region and then user able to add changes to the entire colour boundary at the same time.
![screenshot from 2015-06-23 00 54 59](https://cloud.githubusercontent.com/assets/5234677/8291091/d72bba4e-1944-11e5-982a-c3016d32cea8.png)
![screenshot from 2015-06-23 00 56 30](https://cloud.githubusercontent.com/assets/5234677/8291098/e406b3a4-1944-11e5-8e53-85c3229a626f.png)

2. Adding basic pattern editor tools for cropping,rotating of the pattern. In the current implementation there is a preview of the pattern is shown when the cropping of the image is done. User has to click on the crop button and then the cropping is enabled on the image. Rotating of the image can be done in both clockwise and anti clockwise.
Improvements to be done: Adding a tool bar for the basic patten editor tools.
![screenshot from 2015-06-23 00 50 14](https://cloud.githubusercontent.com/assets/5234677/8291225/ce3254f6-1945-11e5-9276-4fd09b2018fb.png)
![screenshot from 2015-06-23 00 52 44](https://cloud.githubusercontent.com/assets/5234677/8291236/de23aedc-1945-11e5-922f-b17272b05d45.png)

**Comment by mariobehling** [comment]
Awesome!
